An-Labo/An-Labo-NailTool

Packages/world.anlabo.mdnailtool/Editor/NailDesigns/NailProcessorBase.cs, Packages/world.anlabo.mdnailtool/Editor/NailSetupProcessor.cs, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/LineyStellaNail/Point/Taurus/[mat][LineyStellaNail][lil-toon]Taurus_point_Thumb.L.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/LineyStellaNail/Square/Taurus/[mat][LineyStellaNail][lil-toon]Taurus_square_Thumb.L.mat, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
- LineyStellaNailのマテリアル修正
- ModularAvatarのBoneProxyが、Toeがマッピングされていないアバターに対して、機能しないための応急処置
- 生成されたマテリアルの名前に日付が付与されていないため上書き保存されてしまう問題の修正
=> Release 0.8.3

Assets/An-Labo/MDnailTool/Test.unity, Packages/world.anlabo.mdnailtool/Editor/AvatarMatching.cs, Packages/world.anlabo.mdnailtool/Editor/Entity/AvatarVariation.cs, Packages/world.anlabo.mdnailtool/Editor/MDNailToolDefines.cs, Packages/world.anlabo.mdnailtool/Editor/NailSetupProcessor.cs, Packages/world.anlabo.mdnailtool/Editor/VisualElements/AvatarDropDowns.cs, Packages/world.anlabo.mdnailtool/Editor/Window/MDNailToolWindow.cs, Packages/world.anlabo.mdnailtool/Editor/Window/MDnailToolWindow.uxml, Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
- ツールウィンドウのバージョン情報を`package.json`から取得するように
- prefabGUID -> nailPrefabGUID へ変更
- 各ネイル形状毎にプレハブが用意されている場合、置き換えるように
- FbxのGUIDベースマッチングの修正
- Prefabベースのマッチング処理の修正
=> Release 0.8.5

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/CURISHIA.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/CURISHIA/[Natural]CURISHIA.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/CURISHIA/[Natural]CURISHIA.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/CURISHIA/[Oval]CURISHIA.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/CURISHIA/[Oval]CURISHIA.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Perula.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Perula/[Natural]Perula.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Perula/[Natural]Perula.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Perula/[Oval]Perula.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Perula/[Oval]Perula.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Perula/[Point]Perula.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Perula/[Point]Perula.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Senbyo.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Senbyo/[Natural]Senbyo.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Senbyo/[Natural]Senbyo.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Senbyo/[Oval]Senbyo.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Senbyo/[Oval]Senbyo.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Senbyo/[Point]Senbyo.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Senbyo/[Point]Senbyo.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルナール.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルナール/[Natural]ルナール.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルナール/[Natural]ルナール.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルナール/[Oval]ルナール.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルナール/[Oval]ルナール.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルナール/[Point]ルナール.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルナール/[Point]ルナール.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
・ショップ順を降順に変更
・ルナール対応追加
・ペルラ対応追加
・仙猫対応追加
・キュリシア対応追加
=> Release 0.8.9

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv1.11.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv1.11/[Natural]リルモワv1.11.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv1.11/[Natural]リルモワv1.11.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv1.11/[Oval]リルモワv1.11.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv1.11/[Oval]リルモワv1.11.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv2.0.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv2.0/[Natural]リルモワv2.0.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv2.0/[Natural]リルモワv2.0.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv2.0/[Oval]リルモワv2.0.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv2.0/[Oval]リルモワv2.0.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.10

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.15

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/めいゆん_toe_heel100/[Natural]めいゆん_toe_heel100.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/めいゆん_toe_heel100/[Natural]めいゆん_toe_heel100.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/めいゆん_toe_heel100/[Oval]めいゆん_toe_heel100.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/めいゆん_toe_heel100/[Oval]めいゆん_toe_heel100.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/めいゆん_toe_heel65/[Natural]めいゆん_toe_heel65.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/めいゆん_toe_heel65/[Natural]めいゆん_toe_heel65.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/めいゆん_toe_heel65/[Oval]めいゆん_toe_heel65.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/めいゆん_toe_heel65/[Oval]めいゆん_toe_heel65.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
+ support めいゆん toe_heel 65 and 100
=> Release 0.8.18

Packages/world.anlabo.mdnailtool/Resource/DB/nailDesign.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#025.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#025/[mat][DailyNail][lil-toon]#025_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#025/[mat][DailyNail][lil-toon]#025_natural.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#025/[mat][DailyNail][lil-toon]#025_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#025/[mat][DailyNail][lil-toon]#025_oval.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#025/[mat][DailyNail][lil-toon]#025_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#025/[mat][DailyNail][lil-toon]#025_point.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#025/[mat][DailyNail][lil-toon]#025_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#025/[mat][DailyNail][lil-toon]#025_square.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#026.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#026/[mat][DailyNail][lil-toon]#026_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#026/[mat][DailyNail][lil-toon]#026_natural.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#026/[mat][DailyNail][lil-toon]#026_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#026/[mat][DailyNail][lil-toon]#026_oval.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#026/[mat][DailyNail][lil-toon]#026_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#026/[mat][DailyNail][lil-toon]#026_point.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#026/[mat][DailyNail][lil-toon]#026_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#026/[mat][DailyNail][lil-toon]#026_square.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#027.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#027/[mat][DailyNail][lil-toon]#027_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#027/[mat][DailyNail][lil-toon]#027_natural.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#027/[mat][DailyNail][lil-toon]#027_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#027/[mat][DailyNail][lil-toon]#027_oval.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#027/[mat][DailyNail][lil-toon]#027_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#027/[mat][DailyNail][lil-toon]#027_point.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#027/[mat][DailyNail][lil-toon]#027_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#027/[mat][DailyNail][lil-toon]#027_square.mat.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.22

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/MARUBODY_Foot_Highheel_1/[Natural]MARUBODY_Foot_Highheel_1.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/MARUBODY_Foot_Highheel_1/[Natural]MARUBODY_Foot_Highheel_1.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/MARUBODY_Foot_Highheel_2/[Natural]MARUBODY_Foot_Highheel_2.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/MARUBODY_Foot_Highheel_2/[Natural]MARUBODY_Foot_Highheel_2.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/MARUBODY_Foot_Highheel_3/[Natural]MARUBODY_Foot_Highheel_3.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/MARUBODY_Foot_Highheel_3/[Natural]MARUBODY_Foot_Highheel_3.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
+ MARUBODY Highheel_1
+ MARUBODY Highheel_2
+ MARUBODY Highheel_3
=> Release 0.8.24

Packages/world.anlabo.mdnailtool/Resource/DB/nailDesign.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#028.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#028/[mat][DailyNail][lil-toon]#028_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#028/[mat][DailyNail][lil-toon]#028_natural.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#028/[mat][DailyNail][lil-toon]#028_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#028/[mat][DailyNail][lil-toon]#028_oval.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#028/[mat][DailyNail][lil-toon]#028_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#028/[mat][DailyNail][lil-toon]#028_point.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#028/[mat][DailyNail][lil-toon]#028_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#028/[mat][DailyNail][lil-toon]#028_square.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#029.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#029/[mat][DailyNail][lil-toon]#029_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#029/[mat][DailyNail][lil-toon]#029_natural.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#029/[mat][DailyNail][lil-toon]#029_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#029/[mat][DailyNail][lil-toon]#029_oval.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#029/[mat][DailyNail][lil-toon]#029_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#029/[mat][DailyNail][lil-toon]#029_point.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#029/[mat][DailyNail][lil-toon]#029_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#029/[mat][DailyNail][lil-toon]#029_square.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#030.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#030/[mat][DailyNail][lil-toon]#030_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#030/[mat][DailyNail][lil-toon]#030_natural.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#030/[mat][DailyNail][lil-toon]#030_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#030/[mat][DailyNail][lil-toon]#030_oval.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#030/[mat][DailyNail][lil-toon]#030_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#030/[mat][DailyNail][lil-toon]#030_point.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#030/[mat][DailyNail][lil-toon]#030_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#030/[mat][DailyNail][lil-toon]#030_square.mat.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.25

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Julius/[Natural]Julius.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Julius/[Natural]Julius.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Julius/[Oval]Julius.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Julius/[Oval]Julius.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.27

Packages/world.anlabo.mdnailtool/package.json
=> Relase 0.8.31

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Chiffon_Foot_HighHeel/[Natural]Chiffon_Foot_HighHeel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Chiffon_Foot_HighHeel/[Natural]Chiffon_Foot_HighHeel.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Chiffon_Foot_HighHeel/[Oval]Chiffon_Foot_HighHeel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Chiffon_Foot_HighHeel/[Oval]Chiffon_Foot_HighHeel.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
+Chiffon Foot_HighHeel
*Mellotron, Nenmir, Munkki fix
=> Release 0.8.37

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Milk_Sugar_latte/[Natural]Milk_Sugar_latte.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Milk_Sugar_latte/[Oval]Milk_Sugar_latte.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/rurune/[Natural]rurune.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/rurune/[Natural]rurune.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/rurune/[Oval]rurune.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/rurune/[Oval]rurune.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/rurune/[Point]rurune.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/rurune/[Point]rurune.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.48

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv2.11/[Natural]リルモワv2.11.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv2.11/[Natural]リルモワv2.11.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv2.11/[Oval]リルモワv2.11.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv2.11/[Oval]リルモワv2.11.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
+Liloumois 2.11
+lise MARUBODY 2.0
=> Release 0.8.51

Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Falria/[Natural]Falria.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Falria/[Oval]Falria.prefab, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.53

Packages/world.anlabo.mdnailtool/Resource/DB/nailDesign.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.55

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Flare/[Natural]Flare.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Flare/[Natural]Flare.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Flare/[Oval]Flare.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Flare/[Oval]Flare.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.56

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Julius 2.0 A/[Natural]Julius 2.0 A.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Julius 2.0 A/[Natural]Julius 2.0 A.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Julius 2.0 A/[Oval]Julius 2.0 A.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Julius 2.0 A/[Oval]Julius 2.0 A.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Julius 2.0/[Natural]Julius 2.0.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Julius 2.0/[Natural]Julius 2.0.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Julius 2.0/[Oval]Julius 2.0.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Julius 2.0/[Oval]Julius 2.0.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.60

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Airi/[Natural]Airi.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Airi/[Natural]Airi.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Airi/[Oval]Airi.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Airi/[Oval]Airi.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Airi_High heels_OFF/[Natural]Airi_High heels_OFF.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Airi_High heels_OFF/[Natural]Airi_High heels_OFF.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Airi_High heels_OFF/[Oval]Airi_High heels_OFF.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Airi_High heels_OFF/[Oval]Airi_High heels_OFF.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Airi_High heels_ON/[Natural]Airi_High heels_ON.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Airi_High heels_ON/[Natural]Airi_High heels_ON.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Airi_High heels_ON/[Oval]Airi_High heels_ON.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Airi_High heels_ON/[Oval]Airi_High heels_ON.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Airi_High heels_Toe/[Natural]Airi_High heels_Toe.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Airi_High heels_Toe/[Natural]Airi_High heels_Toe.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Airi_High heels_Toe/[Oval]Airi_High heels_Toe.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Airi_High heels_Toe/[Oval]Airi_High heels_Toe.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
+ Airi / Highheels_Toe / Highheels_ON / Highheels_OFF
- unuse folder
=> Release 0.8.63

Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/rurune/[Natural]rurune.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/rurune/[Oval]rurune.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/rurune/[Point]rurune.prefab, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.64

Packages/world.anlabo.mdnailtool/Resource/Nail/Design/AsagaoNail/[mat][AsagaoNail][lil-toon]natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/AsagaoNail/[mat][AsagaoNail][lil-toon]natural.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/AsagaoNail/[mat][AsagaoNail][lil-toon]oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/AsagaoNail/[mat][AsagaoNail][lil-toon]oval.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/AsagaoNail/[mat][AsagaoNail][lil-toon]point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/AsagaoNail/[mat][AsagaoNail][lil-toon]point.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/AsagaoNail/[mat][AsagaoNail][lil-toon]square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/AsagaoNail/[mat][AsagaoNail][lil-toon]square.mat.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.69

docs/vpm.json
=> Release 0.8.70

Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.71

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/FruityNail/[mat][FruityNail][lil-toon]natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/FruityNail/[mat][FruityNail][lil-toon]natural.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/FruityNail/[mat][FruityNail][lil-toon]oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/FruityNail/[mat][FruityNail][lil-toon]oval.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/FruityNail/[mat][FruityNail][lil-toon]point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/FruityNail/[mat][FruityNail][lil-toon]point.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/FruityNail/[mat][FruityNail][lil-toon]square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/FruityNail/[mat][FruityNail][lil-toon]square.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Gizmo/[Natural]Gizmo.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Gizmo/[Natural]Gizmo.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Gizmo/[Oval]Gizmo.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Gizmo/[Oval]Gizmo.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Noiz/[Natural]Noiz.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Noiz/[Natural]Noiz.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Noiz/[Oval]Noiz.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Noiz/[Oval]Noiz.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/[Sample]/Sample.txt, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/[Sample]/[Oval]Sample.Lonly.prefab, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.72

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.73

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Anri/[Natural]Anri.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Anri/[Oval]Anri.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Anri/[Point]Anri.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Anri/[Square]Anri.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Anri_men/[Natural]Anri_men.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Anri_men/[Oval]Anri_men.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Anri_men/[Point]Anri_men.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Anri_men/[Square]Anri_men.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Kikyo ver1.03/[Natural]Kikyo ver1.03.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Kikyo ver1.03/[Oval]Kikyo ver1.03.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Kikyo/[Natural]Kikyo.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Kikyo/[Oval]Kikyo.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Kikyo_Toe_highheels/[Natural]Kikyo_Toe_highheels.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Kikyo_Toe_highheels/[Oval]Kikyo_Toe_highheels.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Minase/[Natural]Minase.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Minase/[Oval]Minase.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Minase/[Point]Minase.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Minase/[Square]Minase.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mizuki/[Natural]Mizuki.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mizuki/[Oval]Mizuki.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mizuki/[Point]Mizuki.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.74

Packages/world.anlabo.mdnailtool/Resource/DB/nailDesign.json, Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#065/[mat][DailyNail][lil-toon]#065_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#065/[mat][DailyNail][lil-toon]#065_natural.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#065/[mat][DailyNail][lil-toon]#065_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#065/[mat][DailyNail][lil-toon]#065_oval.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#065/[mat][DailyNail][lil-toon]#065_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#065/[mat][DailyNail][lil-toon]#065_point.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#065/[mat][DailyNail][lil-toon]#065_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#065/[mat][DailyNail][lil-toon]#065_square.mat.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.76

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Aniath/[Natural]Aniath.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Aniath/[Natural]Aniath.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Aniath/[Oval]Aniath.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Aniath/[Oval]Aniath.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.78

Packages/world.anlabo.mdnailtool/Resource/DB/nailDesign.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
fix SpookyMagnetNail Thumbnail
=> Release 0.8.80

Packages/world.anlabo.mdnailtool/Resource/DB/nailDesign.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#066/[mat][DailyNail][lil-toon]#066_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#066/[mat][DailyNail][lil-toon]#066_natural.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#066/[mat][DailyNail][lil-toon]#066_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#066/[mat][DailyNail][lil-toon]#066_oval.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#066/[mat][DailyNail][lil-toon]#066_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#066/[mat][DailyNail][lil-toon]#066_point.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#066/[mat][DailyNail][lil-toon]#066_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#066/[mat][DailyNail][lil-toon]#066_square.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#067/[mat][DailyNail][lil-toon]#067_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#067/[mat][DailyNail][lil-toon]#067_natural.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#067/[mat][DailyNail][lil-toon]#067_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#067/[mat][DailyNail][lil-toon]#067_oval.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#067/[mat][DailyNail][lil-toon]#067_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#067/[mat][DailyNail][lil-toon]#067_point.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#067/[mat][DailyNail][lil-toon]#067_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#067/[mat][DailyNail][lil-toon]#067_square.mat.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Relase 0.8.81

Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.87

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Astel/[Natural]Astel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Astel/[Natural]Astel.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Astel/[Oval]Astel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Astel/[Oval]Astel.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/あのん_Highheel/[Natural]あのん_Highheel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/あのん_Highheel/[Natural]あのん_Highheel.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/あのん_Highheel/[Oval]あのん_Highheel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/あのん_Highheel/[Oval]あのん_Highheel.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.91

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.98

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/セレスティア_RemovedNail/[Natural]セレスティア_RemovedNail.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/セレスティア_RemovedNail/[Natural]セレスティア_RemovedNail.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/セレスティア_RemovedNail/[Oval]セレスティア_RemovedNail.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/セレスティア_RemovedNail/[Oval]セレスティア_RemovedNail.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
Add Selestia Removed Nail Prefab
=> Release 0.8.99

Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.103

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/LAMBDA/[Natural]LAMBDA.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/LAMBDA/[Natural]LAMBDA.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/LAMBDA/[Oval]LAMBDA.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/LAMBDA/[Oval]LAMBDA.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/LETHALFREET/[Natural]LETHALFREET.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/LETHALFREET/[Natural]LETHALFREET.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/LETHALFREET/[Oval]LETHALFREET.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/LETHALFREET/[Oval]LETHALFREET.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Lilimoca/[Natural]Lilimoca.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Lilimoca/[Natural]Lilimoca.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Lilimoca/[Oval]Lilimoca.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Lilimoca/[Oval]Lilimoca.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Malion/[Natural]Malion.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Malion/[Natural]Malion.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Malion/[Oval]Malion.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Malion/[Oval]Malion.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Sii/[Nautral]Sii.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Sii/[Nautral]Sii.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Sii/[Oval]Sii.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Sii/[Oval]Sii.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
Add Sii Phi Malion Lilimoca LETHALFREET LAMBDA
=> Release 0.8.106

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SELESTIA/[Natural]SELESTIA.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SELESTIA/[Natural]SELESTIA.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SELESTIA/[Oval]SELESTIA.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SELESTIA/[Oval]SELESTIA.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SELESTIA/[Point]SELESTIA.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SELESTIA/[Point]SELESTIA.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SELESTIA_RemovedNail/[Natural]SELESTIA_RemovedNail.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SELESTIA_RemovedNail/[Natural]SELESTIA_RemovedNail.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SELESTIA_RemovedNail/[Oval]SELESTIA_RemovedNail.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SELESTIA_RemovedNail/[Oval]SELESTIA_RemovedNail.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SELESTIA_RemovedNail_Foot_hiil/[Natural]SELESTIA_RemovedNail_Foot_hiil.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SELESTIA_RemovedNail_Foot_hiil/[Natural]SELESTIA_RemovedNail_Foot_hiil.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SELESTIA_RemovedNail_Foot_hiil/[Oval]SELESTIA_RemovedNail_Foot_hiil.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SELESTIA_RemovedNail_Foot_hiil/[Oval]SELESTIA_RemovedNail_Foot_hiil.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.107

Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.109

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/sairou/[Natural]sairou.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/sairou/[Oval]sairou.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.110

Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/sairou/[Natural]sairou.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/sairou/[Oval]sairou.prefab, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.111

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv2.21/[Natural]リルモワv2.21.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv2.21/[Natural]リルモワv2.21.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv2.21/[Oval]リルモワv2.21.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/リルモワv2.21/[Oval]リルモワv2.21.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.115

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.117

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.118

Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-falling star/[mat][WeatherNail-falling star][lil-toon]shooting star.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-falling star/[mat][WeatherNail-falling star][lil-toon]shooting star.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-rain/[mat][WeatherNail-rain][lil-toon]falling rain1.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-rain/[mat][WeatherNail-rain][lil-toon]falling rain1.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-rain/[mat][WeatherNail-rain][lil-toon]falling rain2.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-rain/[mat][WeatherNail-rain][lil-toon]falling rain2.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-rain/[mat][WeatherNail-rain][lil-toon]falling rain3.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-rain/[mat][WeatherNail-rain][lil-toon]falling rain3.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-rain/[mat][WeatherNail-rain][lil-toon]falling rain4.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-rain/[mat][WeatherNail-rain][lil-toon]falling rain4.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-snow/[mat][WeatherNail-snow][lil-toon]falling snow1.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-snow/[mat][WeatherNail-snow][lil-toon]falling snow1.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-snow/[mat][WeatherNail-snow][lil-toon]falling snow2.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-snow/[mat][WeatherNail-snow][lil-toon]falling snow2.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-snow/[mat][WeatherNail-snow][lil-toon]falling snow3.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-snow/[mat][WeatherNail-snow][lil-toon]falling snow3.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-snow/[mat][WeatherNail-snow][lil-toon]falling snow4.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/WeatherNail-snow/[mat][WeatherNail-snow][lil-toon]falling snow4.mat.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.120

Packages/world.anlabo.mdnailtool/Editor/LegacyDesignInstaller.cs, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.121

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka/[Natural]ririka.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka/[Natural]ririka.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka/[Oval]ririka.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka/[Oval]ririka.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka/[Point]ririka.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka/[Point]ririka.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka_heel_OFF_ヒールオフ/[Natural]ririka_heel_OFF_ヒールオフ.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka_heel_OFF_ヒールオフ/[Natural]ririka_heel_OFF_ヒールオフ.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka_heel_OFF_ヒールオフ/[Oval]ririka_heel_OFF_ヒールオフ.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka_heel_OFF_ヒールオフ/[Oval]ririka_heel_OFF_ヒールオフ.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka_heel_OFF_ヒールオフ/[Point]ririka_heel_OFF_ヒールオフ.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka_heel_OFF_ヒールオフ/[Point]ririka_heel_OFF_ヒールオフ.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka_highheel_ハイヒール/[Natural]ririka_highheel_ハイヒール.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka_highheel_ハイヒール/[Natural]ririka_highheel_ハイヒール.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka_highheel_ハイヒール/[Oval]ririka_highheel_ハイヒール.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka_highheel_ハイヒール/[Oval]ririka_highheel_ハイヒール.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka_highheel_ハイヒール/[Point]ririka_highheel_ハイヒール.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ririka_highheel_ハイヒール/[Point]ririka_highheel_ハイヒール.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.131

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Yoll_v4_31_Tpose/[Natural]Yoll_v4_31_Tpose.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Yoll_v4_31_Tpose/[Natural]Yoll_v4_31_Tpose.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Yoll_v4_31_Tpose/[Oval]Yoll_v4_31_Tpose.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Yoll_v4_31_Tpose/[Oval]Yoll_v4_31_Tpose.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Yoll_v4_31_Tpose_munenashi/[Natural]Yoll_v4_31_Tpose_munenashi.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Yoll_v4_31_Tpose_munenashi/[Natural]Yoll_v4_31_Tpose_munenashi.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Yoll_v4_31_Tpose_munenashi/[Oval]Yoll_v4_31_Tpose_munenashi.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Yoll_v4_31_Tpose_munenashi/[Oval]Yoll_v4_31_Tpose_munenashi.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.132

Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.135

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/9b3d/[Natural]9b3d.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/9b3d/[Natural]9b3d.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/9b3d/[Oval]9b3d.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/9b3d/[Oval]9b3d.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/9b3d_heel_up/[Natural]9b3d_heel_up.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/9b3d_heel_up/[Natural]9b3d_heel_up.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/9b3d_heel_up/[Oval]9b3d_heel_up.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/9b3d_heel_up/[Oval]9b3d_heel_up.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/9b3d_toe_up/[Natural]9b3d_toe_up.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/9b3d_toe_up/[Natural]9b3d_toe_up.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/9b3d_toe_up/[Oval]9b3d_toe_up.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/9b3d_toe_up/[Oval]9b3d_toe_up.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/シリウス/[Oval]シリウス.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/シリウス/[Point]シリウス.prefab, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.136

Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.138

Packages/world.anlabo.mdnailtool/Resource/DB/nailDesign.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#108/[mat][DailyNail][lil-toon]#108_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#108/[mat][DailyNail][lil-toon]#108_natural.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#108/[mat][DailyNail][lil-toon]#108_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#108/[mat][DailyNail][lil-toon]#108_oval.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#108/[mat][DailyNail][lil-toon]#108_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#108/[mat][DailyNail][lil-toon]#108_point.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#108/[mat][DailyNail][lil-toon]#108_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#108/[mat][DailyNail][lil-toon]#108_square.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/MilkyNail/[mat][MilkyNail][lil-toon]natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/MilkyNail/[mat][MilkyNail][lil-toon]natural.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/MilkyNail/[mat][MilkyNail][lil-toon]oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/MilkyNail/[mat][MilkyNail][lil-toon]oval.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/MilkyNail/[mat][MilkyNail][lil-toon]point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/MilkyNail/[mat][MilkyNail][lil-toon]point.mat.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/MilkyNail/[mat][MilkyNail][lil-toon]square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/MilkyNail/[mat][MilkyNail][lil-toon]square.mat.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
Add MilkyNail
Add DailyNail 108
=> Release 0.8.141

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia/[Natural]Marycia.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia/[Natural]Marycia.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia/[Oval]Marycia.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia/[Oval]Marycia.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_Foot_Flat/[Natural]Marycia_Foot_Flat.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_Foot_Flat/[Natural]Marycia_Foot_Flat.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_Foot_Flat/[Oval]Marycia_Foot_Flat.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_Foot_Flat/[Oval]Marycia_Foot_Flat.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_Heel_Foot/[Natural]Marycia_Heel_Foot.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_Heel_Foot/[Natural]Marycia_Heel_Foot.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_Heel_Foot/[Oval]Marycia_Heel_Foot.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_Heel_Foot/[Oval]Marycia_Heel_Foot.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_Heel_Toe/[Natural]Marycia_Heel_Toe.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_Heel_Toe/[Natural]Marycia_Heel_Toe.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_Heel_Toe/[Oval]Marycia_Heel_Toe.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_Heel_Toe/[Oval]Marycia_Heel_Toe.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.142

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia/[Natural]Marycia.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_Foot_Flat/[Natural]Marycia_Foot_Flat.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_Heel_Foot/[Natural]Marycia_Heel_Foot.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_T/[Natural]Marycia_T.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_T/[Natural]Marycia_T.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_T/[Oval]Marycia_T.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_T/[Oval]Marycia_T.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_T_Foot_Flat/[Natural]Marycia_T_Foot_Flat.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_T_Foot_Flat/[Natural]Marycia_T_Foot_Flat.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_T_Foot_Flat/[Oval]Marycia_T_Foot_Flat.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_T_Foot_Flat/[Oval]Marycia_T_Foot_Flat.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_T_Heel_Foot/[Natural]Marycia_T_Heel_Foot.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_T_Heel_Foot/[Natural]Marycia_T_Heel_Foot.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_T_Heel_Foot/[Oval]Marycia_T_Heel_Foot.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_T_Heel_Foot/[Oval]Marycia_T_Heel_Foot.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_T_Heel_Toe/[Natural]Marycia_T_Heel_Toe.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_T_Heel_Toe/[Natural]Marycia_T_Heel_Toe.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_T_Heel_Toe/[Oval]Marycia_T_Heel_Toe.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Marycia_T_Heel_Toe/[Oval]Marycia_T_Heel_Toe.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
Add Marycia_T
fix Marycia_natural
=> Release 0.8.143

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.146

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.147

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Milltina_1.01/[Natural]Milltina_1.01.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Milltina_1.01/[Natural]Milltina_1.01.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Milltina_1.01/[Oval]Milltina_1.01.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Milltina_1.01/[Oval]Milltina_1.01.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Milltina_1.01_Foot_heel/[Natural]Milltina_1.01_Foot_heel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Milltina_1.01_Foot_heel/[Natural]Milltina_1.01_Foot_heel.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Milltina_1.01_Foot_heel/[Oval]Milltina_1.01_Foot_heel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Milltina_1.01_Foot_heel/[Oval]Milltina_1.01_Foot_heel.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.150

Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.154

Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#121/[mat][DailyNail][lil-toon]#121_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#121/[mat][DailyNail][lil-toon]#121_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#121/[mat][DailyNail][lil-toon]#121_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#121/[mat][DailyNail][lil-toon]#121_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#122/[mat][DailyNail][lil-toon]#122_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#122/[mat][DailyNail][lil-toon]#122_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#122/[mat][DailyNail][lil-toon]#122_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#122/[mat][DailyNail][lil-toon]#122_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#123/[mat][DailyNail][lil-toon]#123_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#123/[mat][DailyNail][lil-toon]#123_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#123/[mat][DailyNail][lil-toon]#123_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#123/[mat][DailyNail][lil-toon]#123_square.mat, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.155

Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#124/[mat][DailyNail][lil-toon]#124_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#124/[mat][DailyNail][lil-toon]#124_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#124/[mat][DailyNail][lil-toon]#124_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#124/[mat][DailyNail][lil-toon]#124_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#125/[mat][DailyNail][lil-toon]#125_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#125/[mat][DailyNail][lil-toon]#125_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#125/[mat][DailyNail][lil-toon]#125_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#125/[mat][DailyNail][lil-toon]#125_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#126/[mat][DailyNail][lil-toon]#126_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#126/[mat][DailyNail][lil-toon]#126_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#126/[mat][DailyNail][lil-toon]#126_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#126/[mat][DailyNail][lil-toon]#126_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#127/[mat][DailyNail][lil-toon]#127_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#127/[mat][DailyNail][lil-toon]#127_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#127/[mat][DailyNail][lil-toon]#127_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#127/[mat][DailyNail][lil-toon]#127_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#128/[mat][DailyNail][lil-toon]#128_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#128/[mat][DailyNail][lil-toon]#128_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#128/[mat][DailyNail][lil-toon]#128_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#128/[mat][DailyNail][lil-toon]#128_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#129/[mat][DailyNail][lil-toon]#129_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#129/[mat][DailyNail][lil-toon]#129_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#129/[mat][DailyNail][lil-toon]#129_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#129/[mat][DailyNail][lil-toon]#129_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#130/[mat][DailyNail][lil-toon]#130_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#130/[mat][DailyNail][lil-toon]#130_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#130/[mat][DailyNail][lil-toon]#130_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#130/[mat][DailyNail][lil-toon]#130_square.mat, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.159

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.161

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/NanaseNoir_v1.3/[Natural]NanaseNoir_v1.3.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/NanaseNoir_v1.3/[Natural]NanaseNoir_v1.3.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/NanaseNoir_v1.4/[Natural]NanaseNoir_v1.4.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/NanaseNoir_v1.4/[Natural]NanaseNoir_v1.4.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/NanaseNoir_v1.4/[Oval]NanaseNoir_v1.4.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/NanaseNoir_v1.4/[Oval]NanaseNoir_v1.4.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/NanaseNoir_v1.4/[Point]NanaseNoir_v1.4.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/NanaseNoir_v1.4/[Point]NanaseNoir_v1.4.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/NanaseNoir_v1.4_high heels/[Natural]NanaseNoir_v1.4_high heels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/NanaseNoir_v1.4_high heels/[Natural]NanaseNoir_v1.4_high heels.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/NanaseNoir_v1.4_high heels/[Oval]NanaseNoir_v1.4_high heels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/NanaseNoir_v1.4_high heels/[Oval]NanaseNoir_v1.4_high heels.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/NanaseNoir_v1.4_high heels/[Point]NanaseNoir_v1.4_high heels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/NanaseNoir_v1.4_high heels/[Point]NanaseNoir_v1.4_high heels.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.163

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Relase 0.8.164

Packages/world.anlabo.mdnailtool/Resource/Nail/Design/FruityNail/[mat][FruityNail][lil-toon]square.mat, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.165

Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#066/[mat][DailyNail][lil-toon]#066_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#067/[mat][DailyNail][lil-toon]#067_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/FruityNail/[mat][FruityNail][lil-toon]square.mat, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Relase 0.8.167

Packages/world.anlabo.mdnailtool/Resource/Nail/Design/FruityNail/[mat][FruityNail][lil-toon]square.mat, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.168

Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#066/[mat][DailyNail][lil-toon]#066_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#067/[mat][DailyNail][lil-toon]#067_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#131/[mat][DailyNail][lil-toon]#131_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#131/[mat][DailyNail][lil-toon]#131_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#131/[mat][DailyNail][lil-toon]#131_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#131/[mat][DailyNail][lil-toon]#131_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#132/[mat][DailyNail][lil-toon]#132_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#132/[mat][DailyNail][lil-toon]#132_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#132/[mat][DailyNail][lil-toon]#132_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#132/[mat][DailyNail][lil-toon]#132_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#133/[mat][DailyNail][lil-toon]#133_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#133/[mat][DailyNail][lil-toon]#133_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#133/[mat][DailyNail][lil-toon]#133_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#133/[mat][DailyNail][lil-toon]#133_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#134/[mat][DailyNail][lil-toon]#134_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#134/[mat][DailyNail][lil-toon]#134_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#134/[mat][DailyNail][lil-toon]#134_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#134/[mat][DailyNail][lil-toon]#134_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#135/[mat][DailyNail][lil-toon]#135_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#135/[mat][DailyNail][lil-toon]#135_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#135/[mat][DailyNail][lil-toon]#135_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#135/[mat][DailyNail][lil-toon]#135_square.mat, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
fix bugs
Add DailyNail 131-135
=> Release 0.8.169

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Lys/[Natural]Lys.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Lys/[Natural]Lys.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Lys/[Oval]Lys.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Lys/[Oval]Lys.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Lys_Foot_Small/[Natural]Lys_Foot_Small.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Lys_Foot_Small/[Natural]Lys_Foot_Small.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Lys_Foot_Small/[Oval]Lys_Foot_Small.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Lys_Foot_Small/[Oval]Lys_Foot_Small.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mimi/[Natural]Mimi.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mimi/[Natural]Mimi.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mimi/[Oval]Mimi.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mimi/[Oval]Mimi.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mimi/[Point]Mimi.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mimi/[Point]Mimi.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.171

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/椎名_high_heels/[Natural]椎名_high_heels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/椎名_high_heels/[Natural]椎名_high_heels.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/椎名_high_heels/[Oval]椎名_high_heels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/椎名_high_heels/[Oval]椎名_high_heels.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
Add shiina high_heels shapekey
=> Release 0.8.174

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
Add Kosame INABA high heels shapekey
=> Release 0.8.175

Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#136/[mat][DailyNail][lil-toon]#136_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#136/[mat][DailyNail][lil-toon]#136_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#136/[mat][DailyNail][lil-toon]#136_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#136/[mat][DailyNail][lil-toon]#136_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#137/[mat][DailyNail][lil-toon]#137_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#137/[mat][DailyNail][lil-toon]#137_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#137/[mat][DailyNail][lil-toon]#137_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#137/[mat][DailyNail][lil-toon]#137_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#138/[mat][DailyNail][lil-toon]#138_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#138/[mat][DailyNail][lil-toon]#138_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#138/[mat][DailyNail][lil-toon]#138_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#138/[mat][DailyNail][lil-toon]#138_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#139/[mat][DailyNail][lil-toon]#139_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#139/[mat][DailyNail][lil-toon]#139_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#139/[mat][DailyNail][lil-toon]#139_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#139/[mat][DailyNail][lil-toon]#139_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#140/[mat][DailyNail][lil-toon]#139_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#140/[mat][DailyNail][lil-toon]#139_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#140/[mat][DailyNail][lil-toon]#139_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#140/[mat][DailyNail][lil-toon]#139_square.mat, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.176

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_heels/[Natural]ルゼブル_heels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_heels/[Natural]ルゼブル_heels.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_heels/[Oval]ルゼブル_heels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_heels/[Oval]ルゼブル_heels.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_heels/[Point]ルゼブル_heels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_heels/[Point]ルゼブル_heels.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_high heels/[Natural]ルゼブル_high heels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_high heels/[Natural]ルゼブル_high heels.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_high heels/[Oval]ルゼブル_high heels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_high heels/[Oval]ルゼブル_high heels.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_high heels/[Point]ルゼブル_high heels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_high heels/[Point]ルゼブル_high heels.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_more high heels/[Natural]ルゼブル_more high heels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_more high heels/[Natural]ルゼブル_more high heels.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_more high heels/[Oval]ルゼブル_more high heels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_more high heels/[Oval]ルゼブル_more high heels.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_more high heels/[Point]ルゼブル_more high heels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ルゼブル_more high heels/[Point]ルゼブル_more high heels.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.179

Packages/world.anlabo.mdnailtool/Resource/Nail/Design/AuroraNail/[mat][AuroraNail][lil-toon]natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/AuroraNail/[mat][AuroraNail][lil-toon]oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/AuroraNail/[mat][AuroraNail][lil-toon]point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/AuroraNail/[mat][AuroraNail][lil-toon]square.mat, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.180

Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DaisyNail/[mat][DaisyNail][lil-toon]natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DaisyNail/[mat][DaisyNail][lil-toon]oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DaisyNail/[mat][DaisyNail][lil-toon]point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DaisyNail/[mat][DaisyNail][lil-toon]square.mat, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.183

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.185

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#146/[mat][DailyNail][lil-toon]#146_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#146/[mat][DailyNail][lil-toon]#146_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#146/[mat][DailyNail][lil-toon]#146_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#146/[mat][DailyNail][lil-toon]#146_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#147/[mat][DailyNail][lil-toon]#147_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#147/[mat][DailyNail][lil-toon]#147_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#147/[mat][DailyNail][lil-toon]#147_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#147/[mat][DailyNail][lil-toon]#147_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#148/[mat][DailyNail][lil-toon]#148_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#148/[mat][DailyNail][lil-toon]#148_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#148/[mat][DailyNail][lil-toon]#148_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#148/[mat][DailyNail][lil-toon]#148_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#149/[mat][DailyNail][lil-toon]#149_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#149/[mat][DailyNail][lil-toon]#149_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#149/[mat][DailyNail][lil-toon]#149_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#149/[mat][DailyNail][lil-toon]#149_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#150/[mat][DailyNail][lil-toon]#150_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#150/[mat][DailyNail][lil-toon]#150_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#150/[mat][DailyNail][lil-toon]#150_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#150/[mat][DailyNail][lil-toon]#150_square.mat, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
fix NagiyaRuri
add Menno
add DailyNail 146-150
=> Release 0.8.188

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.190

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao/[Natural]mao.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao/[Natural]mao.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao/[Oval]mao.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao/[Oval]mao.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao/[Point]mao.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao/[Point]mao.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao_heel_OFF_ヒールオフ/[Natural]mao_heel_OFF_ヒールオフ.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao_heel_OFF_ヒールオフ/[Natural]mao_heel_OFF_ヒールオフ.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao_heel_OFF_ヒールオフ/[Oval]mao_heel_OFF_ヒールオフ.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao_heel_OFF_ヒールオフ/[Oval]mao_heel_OFF_ヒールオフ.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao_heel_OFF_ヒールオフ/[Point]mao_heel_OFF_ヒールオフ.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao_heel_OFF_ヒールオフ/[Point]mao_heel_OFF_ヒールオフ.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao_highheel_ハイヒール/[Natural]mao_highheel_ハイヒール.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao_highheel_ハイヒール/[Natural]mao_highheel_ハイヒール.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao_highheel_ハイヒール/[Oval]mao_highheel_ハイヒール.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao_highheel_ハイヒール/[Oval]mao_highheel_ハイヒール.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao_highheel_ハイヒール/[Point]mao_highheel_ハイヒール.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/mao_highheel_ハイヒール/[Point]mao_highheel_ハイヒール.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.191

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mao_umikuri/[Natural]Mao_umikuri.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mao_umikuri/[Natural]Mao_umikuri.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mao_umikuri/[Oval]Mao_umikuri.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mao_umikuri/[Oval]Mao_umikuri.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mao_umikuri_Heal/[Natural]Mao_umikuri_Heal.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mao_umikuri_Heal/[Natural]Mao_umikuri_Heal.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mao_umikuri_Heal/[Oval]Mao_umikuri_Heal.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mao_umikuri_Heal/[Oval]Mao_umikuri_Heal.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mao_umikuri_Highheal/[Natural]Mao_umikuri_Highheal.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mao_umikuri_Highheal/[Natural]Mao_umikuri_Highheal.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mao_umikuri_Highheal/[Oval]Mao_umikuri_Highheal.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Mao_umikuri_Highheal/[Oval]Mao_umikuri_Highheal.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.8.194

Assets/An-Labo/MDnailTool/Test.unity, Packages/world.anlabo.mdnailtool/Editor/Window/MDNailToolWindow.cs, Packages/world.anlabo.mdnailtool/Editor/Window/MDnailToolWindow.uxml, Packages/world.anlabo.mdnailtool/Resource/Preview/preview.shader
ついでにUIのスクロール対応
resolve #36 
resolve #34
=> 指の個別設定のトグルで個別のデザイン選択の表示非表示が切り替わる様に

Packages/world.anlabo.mdnailtool/Editor/VisualElements/AvatarDropDowns.cs, Packages/world.anlabo.mdnailtool/Editor/Window/MDNailToolWindow.cs, Packages/world.anlabo.mdnailtool/Editor/Window/MDnailToolWindow.uxml, Packages/world.anlabo.mdnailtool/Editor/Window/SearchAvatarWindow.cs, Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.9.0-beta

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Carroll/[Natural]Carroll.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Carroll/[Natural]Carroll.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Carroll/[Oval]Carroll.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Carroll/[Oval]Carroll.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Carroll_T/[Natural]Carroll_T.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Carroll_T/[Natural]Carroll_T.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Carroll_T/[Oval]Carroll_T.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Carroll_T/[Oval]Carroll_T.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.9.001

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Rei_kyoutuSotai/[Natural]Rei_kyoutuSotai.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Rei_kyoutuSotai/[Natural]Rei_kyoutuSotai.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.9.6

Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SELESTIA_RemovedNail/[Natural]SELESTIA_RemovedNail.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SELESTIA_RemovedNail/[Oval]SELESTIA_RemovedNail.prefab, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.9.7

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Aldona/[Natural]Aldona.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Aldona/[Natural]Aldona.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Aldona/[Oval]Aldona.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Aldona/[Oval]Aldona.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Aldona_Heel/[Natural]Aldona_Heel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Aldona_Heel/[Natural]Aldona_Heel.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Aldona_Heel/[Oval]Aldona_Heel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Aldona_Heel/[Oval]Aldona_Heel.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/DAMI/[Natural]DAMI.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/DAMI/[Natural]DAMI.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/DAMI/[Oval]DAMI.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/DAMI/[Oval]DAMI.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/DAMI_High_heel/[Natural]DAMI_High_heel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/DAMI_High_heel/[Natural]DAMI_High_heel.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/DAMI_High_heel/[Oval]DAMI_High_heel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/DAMI_High_heel/[Oval]DAMI_High_heel.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.9.10

Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#156/[mat][DailyNail][lil-toon]#156_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#156/[mat][DailyNail][lil-toon]#156_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#156/[mat][DailyNail][lil-toon]#156_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#156/[mat][DailyNail][lil-toon]#156_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#157/[mat][DailyNail][lil-toon]#157_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#157/[mat][DailyNail][lil-toon]#157_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#157/[mat][DailyNail][lil-toon]#157_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#157/[mat][DailyNail][lil-toon]#157_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#158/[mat][DailyNail][lil-toon]#158_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#158/[mat][DailyNail][lil-toon]#158_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#158/[mat][DailyNail][lil-toon]#158_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#158/[mat][DailyNail][lil-toon]#158_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#159/[mat][DailyNail][lil-toon]#159_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#159/[mat][DailyNail][lil-toon]#159_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#159/[mat][DailyNail][lil-toon]#159_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#159/[mat][DailyNail][lil-toon]#159_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#160/[mat][DailyNail][lil-toon]#160_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#160/[mat][DailyNail][lil-toon]#160_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#160/[mat][DailyNail][lil-toon]#160_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#160/[mat][DailyNail][lil-toon]#160_square.mat, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.9.11

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.9.17

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SarvaDarsa_SubArm/[Natural]SarvaDarsa_SubArm.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SarvaDarsa_SubArm/[Natural]SarvaDarsa_SubArm.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SarvaDarsa_SubArm/[Oval]SarvaDarsa_SubArm.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/SarvaDarsa_SubArm/[Oval]SarvaDarsa_SubArm.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/TinmeshiTei_Body_ヒール調整用/[Natural]TinmeshiTei_Body_ヒール調整用.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/TinmeshiTei_Body_ヒール調整用/[Natural]TinmeshiTei_Body_ヒール調整用.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/TinmeshiTei_Body_ヒール調整用/[Oval]TinmeshiTei_Body_ヒール調整用.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/TinmeshiTei_Body_ヒール調整用/[Oval]TinmeshiTei_Body_ヒール調整用.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.9.21

Packages/world.anlabo.mdnailtool/Resource/DB/nailDesign.json, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.9.33

Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/TubeRose/[Natural]TubeRose.prefab, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.9.37

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#175/[mat][DailyNail][lil-toon]#175_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#175/[mat][DailyNail][lil-toon]#175_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#175/[mat][DailyNail][lil-toon]#175_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#175/[mat][DailyNail][lil-toon]#175_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#176/[mat][DailyNail][lil-toon]#176_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#176/[mat][DailyNail][lil-toon]#176_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#176/[mat][DailyNail][lil-toon]#176_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#176/[mat][DailyNail][lil-toon]#176_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#177/[mat][DailyNail][lil-toon]#177_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#177/[mat][DailyNail][lil-toon]#177_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#177/[mat][DailyNail][lil-toon]#177_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#177/[mat][DailyNail][lil-toon]#177_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#178/[mat][DailyNail][lil-toon]#178_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#178/[mat][DailyNail][lil-toon]#178_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#178/[mat][DailyNail][lil-toon]#178_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#178/[mat][DailyNail][lil-toon]#178_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#179/[mat][DailyNail][lil-toon]#179_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#179/[mat][DailyNail][lil-toon]#179_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#179/[mat][DailyNail][lil-toon]#179_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#179/[mat][DailyNail][lil-toon]#179_square.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#180/[mat][DailyNail][lil-toon]#180_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#180/[mat][DailyNail][lil-toon]#180_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#180/[mat][DailyNail][lil-toon]#180_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#180/[mat][DailyNail][lil-toon]#180_square.mat, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.9.40

Packages/world.anlabo.mdnailtool/Resource/DB/nailDesign.json, Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ELusion/[Natural]ELusion.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ELusion/[Natural]ELusion.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ELusion/[Oval]ELusion.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/ELusion/[Oval]ELusion.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/matsuriba_remakebody/[Natural]matsuriba_remakebody.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/matsuriba_remakebody/[Natural]matsuriba_remakebody.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
Add ELusion
Add matsuriba remakebody
Add hanka
=> Release 0.9.45

Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#180/[mat][DailyNail][lil-toon]#180_natural.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#180/[mat][DailyNail][lil-toon]#180_oval.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#180/[mat][DailyNail][lil-toon]#180_point.mat, Packages/world.anlabo.mdnailtool/Resource/Nail/Design/DailyNail/#180/[mat][DailyNail][lil-toon]#180_square.mat, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.9.49

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/matsuriba_remakebody/[Natural]matsuriba_remakebody.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Relase 0.9.50

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona/[Natural]Fiona.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona/[Oval]Fiona.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona_1.0/[Natural]Fiona_1.0.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona_1.0/[Natural]Fiona_1.0.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona_1.0/[Oval]Fiona_1.0.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona_1.0/[Oval]Fiona_1.0.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona_2.0_HighHeel/[Natural]Fiona_2.0_HighHeel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona_2.0_HighHeel/[Natural]Fiona_2.0_HighHeel.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona_2.0_HighHeel/[Oval]Fiona_2.0_HighHeel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona_2.0_HighHeel/[Oval]Fiona_2.0_HighHeel.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona_FeetS/[Natural]Fiona_FeetS.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona_FeetS/[Natural]Fiona_FeetS.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona_FeetS/[Oval]Fiona_FeetS.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona_FeetS/[Oval]Fiona_FeetS.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona_FeetS_2.0_HighHeel/[Natural]Fiona_FeetS_2.0_HighHeel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona_FeetS_2.0_HighHeel/[Natural]Fiona_FeetS_2.0_HighHeel.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona_FeetS_2.0_HighHeel/[Oval]Fiona_FeetS_2.0_HighHeel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Fiona_FeetS_2.0_HighHeel/[Oval]Fiona_FeetS_2.0_HighHeel.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.9.52

Packages/world.anlabo.mdnailtool/package.json
=> Release 0.9.54

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Kanata_Toe_heels/[Natural]Kanata_Toe_heels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Kanata_Toe_heels/[Natural]Kanata_Toe_heels.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Kanata_Toe_heels/[Oval]Kanata_Toe_heels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Kanata_Toe_heels/[Oval]Kanata_Toe_heels.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Kanata_Toe_highheels/[Natural]Kanata_Toe_highheels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Kanata_Toe_highheels/[Natural]Kanata_Toe_highheels.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Kanata_Toe_highheels/[Oval]Kanata_Toe_highheels.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Kanata_Toe_highheels/[Oval]Kanata_Toe_highheels.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.9.56

Packages/manifest.json, Packages/packages-lock.json, Packages/world.anlabo.mdnailtool/Editor/VisualElements/NailDesignSelect.cs, Packages/world.anlabo.mdnailtool/Editor/Window/MDNailToolWindow.cs, Packages/world.anlabo.mdnailtool/Resource/uss.meta, Packages/world.anlabo.mdnailtool/Resource/uss/global.uss, Packages/world.anlabo.mdnailtool/Resource/uss/global.uss.meta, ProjectSettings/EditorBuildSettings.asset, ProjectSettings/ProjectSettings.asset, ProjectSettings/ProjectVersion.txt
=> ネイルデザイン名の表示の追加

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Shuan/[Natural]Shuan.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Shuan/[Natural]Shuan.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Shuan/[Oval]Shuan.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Shuan/[Oval]Shuan.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Shuan_Foot_highheel/[Natural]Shuan_Foot_highheel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Shuan_Foot_highheel/[Natural]Shuan_Foot_highheel.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Shuan_Foot_highheel/[Oval]Shuan_Foot_highheel.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Shuan_Foot_highheel/[Oval]Shuan_Foot_highheel.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.9.72

Packages/world.anlabo.mdnailtool/Resource/DB/shop.json, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Pmma/[Natural]Pmma.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Pmma/[Natural]Pmma.prefab.meta, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Pmma/[Oval]Pmma.prefab, Packages/world.anlabo.mdnailtool/Resource/Nail/Prefab/Pmma/[Oval]Pmma.prefab.meta, Packages/world.anlabo.mdnailtool/package.json, docs/vpm.json
=> Release 0.9.74
